#!/bin/sh

ID=com.wordpress.touchcontrol.touchvol
APP_PATH=/media/cryptofs/apps/usr/palm/applications/$ID
#remount root using technique that won't cause the random remounting error
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
	/usr/sbin/rootfs_open -w
fi

/sbin/initctl stop $ID

#remove dbus service file
/bin/rm -f /var/palm/ls2/services/prv/$ID.service
/bin/rm -f /var/palm/ls2/services/pub/$ID.service

/bin/rm -f /var/palm/event.d/$ID
/bin/rm -f $APP_PATH/amixer-default.state
exit 0
