#!/bin/sh

ID=com.wordpress.touchcontrol.touchvol
APP_PATH=/media/cryptofs/apps/usr/palm/applications/$ID
SERVICES_PATH=/media/cryptofs/apps/usr/palm/services/$ID

if [ -z "$IPKG_OFFLINE_ROOT" ]; then
	/usr/sbin/rootfs_open -w
fi

#make directories in the rare event they don't exist
/bin/mkdir -p /var/palm/ls2/services/prv
/bin/mkdir -p /var/palm/ls2/services/pub

#copy dbus service file
/bin/cp -f $SERVICES_PATH/dbus /var/palm/ls2/services/prv/$ID.service
/bin/cp -f $SERVICES_PATH/dbus /var/palm/ls2/services/pub/$ID.service

/bin/mkdir -p /var/palm/event.d

/sbin/initctl stop $ID
/bin/rm -f /var/palm/event.d/$ID
/bin/echo description \"TouchVol Service\" > /var/palm/event.d/$ID
/bin/echo start on stopped finish >> /var/palm/event.d/$ID
/bin/echo exec /usr/sbin/alsactl -f $APP_PATH/amixer-default.state restore 0 >> /var/palm/event.d/$ID
/bin/chmod 755 /var/palm/event.d/$ID

exit 0
